export const accueil = require("../Media/Images/Accueil_01.jpg")
export const favicon = require("../Media/Images/favicon.ico")
export const map_ground = require("../Media/Images/parpaing.jpg")
export const rose = require("../Media/Images/Compass.png")
export const wood = require("../Media/Images/mango.jpg")
